package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// State is everything the bash backend needs to carry out the run. It is
// written as a flat KEY=value file that bash sources; see
// docs/tui-migration.md §4.
//
// Go is the sole parser of the wizard page format: every value here is already
// resolved, so the bash side never re-reads a page file to answer these
// questions.
type State struct {
	App       string
	Action    string
	BuildArgs []string          // already in "--build-arg NAME=value" form
	Variant   string            // .runtime selection value (not its label)
	Pages     map[string][]string // pagename -> selected item names
}

// shellQuote renders a value safe to source from bash inside double quotes.
func shellQuote(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"$", `\$`,
		"`", "\\`",
	)
	return `"` + r.Replace(s) + `"`
}

// varSuffix turns a page name like "00-statusline" into a shell-safe suffix.
func varSuffix(pageName string) string {
	var b strings.Builder
	for _, c := range pageName {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9':
			b.WriteRune(c)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func (s State) Render() string {
	var b strings.Builder
	b.WriteString("# generated by tools-tui -- sourced by lib/wizard.sh\n")
	fmt.Fprintf(&b, "APP=%s\n", shellQuote(s.App))
	fmt.Fprintf(&b, "ACTION=%s\n", shellQuote(s.Action))
	fmt.Fprintf(&b, "BUILD_ARGS=%s\n", shellQuote(strings.Join(s.BuildArgs, " ")))
	fmt.Fprintf(&b, "VARIANT=%s\n", shellQuote(s.Variant))

	names := make([]string, 0, len(s.Pages))
	for k := range s.Pages {
		names = append(names, k)
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(&b, "PAGE_%s=%s\n", varSuffix(n), shellQuote(strings.Join(s.Pages[n], " ")))
	}
	return b.String()
}

// Write persists the state file, creating its directory if needed.
func (s State) Write(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(s.Render()), 0o600)
}

// DefaultStatePath mirrors the location documented in docs/tui-migration.md.
func DefaultStatePath(app string) string {
	base := os.Getenv("XDG_RUNTIME_DIR")
	if base == "" {
		base = os.TempDir()
	}
	return filepath.Join(base, "linux-tools", "wizard-"+app+".state")
}
