package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// State is everything the bash backend needs to carry out the run. It is
// written as a flat KEY=value file that bash sources; see
// docs/tui-migration.md §4.
//
// Go is the sole parser of the wizard page format: every value here is already
// resolved, so the bash side never re-reads a page file to answer these
// questions.
type State struct {
	App       string
	Action    string
	BuildArgs []string            // already in "--build-arg NAME=value" form
	Variant   string              // .runtime selection value (not its label)
	Pages     map[string][]string // pagename -> selected item names
}

// shellQuote renders a value safe to source from bash inside double quotes.
func shellQuote(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"$", `\$`,
		"`", "\\`",
	)
	return `"` + r.Replace(s) + `"`
}

// varSuffix turns a page name like "00-statusline" into a shell-safe suffix.
func varSuffix(pageName string) string {
	var b strings.Builder
	for _, c := range pageName {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9':
			b.WriteRune(c)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func (s State) Render() string {
	var b strings.Builder
	b.WriteString("# generated by tools-tui -- sourced by lib/wizard.sh\n")
	fmt.Fprintf(&b, "APP=%s\n", shellQuote(s.App))
	fmt.Fprintf(&b, "ACTION=%s\n", shellQuote(s.Action))
	fmt.Fprintf(&b, "BUILD_ARGS=%s\n", shellQuote(strings.Join(s.BuildArgs, " ")))
	fmt.Fprintf(&b, "VARIANT=%s\n", shellQuote(s.Variant))

	names := make([]string, 0, len(s.Pages))
	for k := range s.Pages {
		names = append(names, k)
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(&b, "PAGE_%s=%s\n", varSuffix(n), shellQuote(strings.Join(s.Pages[n], " ")))
	}
	return b.String()
}

// Write persists the state file at an exact path, creating its directory if
// needed. WriteNew is what the dashboard uses; this exists for callers that
// have already chosen a path, and for tests.
func (s State) Write(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(s.Render()), 0o600)
}

// WriteNew creates a fresh state file and returns its path.
//
// bash *sources* this file, so a path another local user can influence is a
// way to run commands as whoever is using the dashboard. The file is therefore
// created inside a 0700 directory, with a random name, and with O_EXCL — never
// at a name that can be predicted and pre-created.
func (s State) WriteNew() (string, error) {
	dir, err := stateDir()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	// os.CreateTemp opens with O_CREATE|O_EXCL|0600 and a random suffix.
	f, err := os.CreateTemp(dir, "wizard-"+s.App+"-*.state")
	if err != nil {
		return "", err
	}
	defer f.Close()
	if _, err := f.WriteString(s.Render()); err != nil {
		os.Remove(f.Name())
		return "", err
	}
	return f.Name(), nil
}

// stateDir is under $HOME on purpose.
//
// Distrobox shares $HOME between the container and the host, so a file written
// here is visible to the bash backend even when the dashboard runs inside a
// container. Neither /tmp nor $XDG_RUNTIME_DIR is guaranteed to be the same
// filesystem across that boundary — and a state file the backend cannot read
// means a setup that rebuilds the app while silently discarding every answer.
func stateDir() (string, error) {
	if base := os.Getenv("XDG_CACHE_HOME"); base != "" {
		return filepath.Join(base, "linux-tools", "wizard"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".cache", "linux-tools", "wizard"), nil
}
